matrix:
  include:
    - language: php
      dist: trusty
      php:
        - '7.2'
        - '7.3'
      script:
        - phpunit -c phpunit.example.xml --exclude-group=no-ci-test
      install: composer install --dev
      
    - language: node_js
      node_js:
        - "12.4"
      before_script:
        - npm install grunt-cli -g
      install:
        - npm install
        - composer install --dev
